### ISSUE TITLE
Fail to install with Chef DK 0.4.0

### ISSUE THREAD

**Issue by jbourassa** [BallisticPain/chef-wkhtmltopdf#4]
Hi,

The package failed to install on Chef DK 0.4.0. The issue is described in https://github.com/didacte/chef-wkhtmltopdf/commit/ce4aaae8bc19e428e6dcb060d1213fa25e205de5, along with a fix. I did not open a pull request since I think it still breaks for Windows and OSX, but I did not have any proper test setup for those.

Cheers!

**Comment by liyan1688** [comment]
:+1: I ran into the same issue. The diff helped. But I am not expert for windows either. It would be nice to merge in this change properly. I am keeping a local diff for now.

**Comment by BallisticPain** [comment]
I'll peek into this. Thanks for letting me know.

**Comment by ikurochkin** [comment]
+1

**Comment by BallisticPain** [comment]
This is fixed in the latest release. 0.4.2.
