### ISSUE TITLE
Sourceforge download throws 404

### ISSUE THREAD

**Issue by harkenn** [BallisticPain/chef-wkhtmltopdf#5]
The linux packages have been removed from sourceforge. I was able to find the debian trusty package at : http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb

**Comment by phcyso** [comment]
Created #6 to update the mirror address

**Comment by BallisticPain** [comment]
Thanks @harkenn & @phcyso. I see the PR. Running through it today. Will have it merged ASAP.

**Comment by BallisticPain** [comment]
This issue is now fixed. Please download the latest.
