### ISSUE TITLE
How to automatically accept/ add dependency to get  xorg-x11-fonts-75dpi

### ISSUE THREAD

**Issue by gxof** [BallisticPain/chef-wkhtmltopdf#9]
Hello, I have the following error and would like to know how I can solve it. 
` 
Mixlib::ShellOut::ShellCommandFailed    
 ------------------------------------
Expected process to exit with [0], but received '1'
 ---- Begin output of rpm  -i /var/chef/cache/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm ----
STDOUT: 
STDERR: error: Failed dependencies:
  xorg-x11-fonts-75dpi is needed by wkhtmltox-1:0.12.2.1-1.x86_64
 ---- End output of rpm  -i /var/chef/cache/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm ----
Ran rpm  -i /var/chef/cache/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm returned 1`

**Comment by BallisticPain** [comment]
I'm guessing you got this sorted?

**Comment by gxof** [comment]
Yes thanks I added a simple a recipe in order to install wkhtmltox, I add -y to yum install when needed. What I wonder is, it seems that the previous wkhtmltopdf cookbook was able to install the package somewhere else than /usr/local/bin and the wkhtmltopdf-update can't. I am right? I try to install to usr/bin and it failed
